const C=window.DASHBOARD_CONFIG||{};let data=[],page=0,pageTimer;
function now(){return new Date(new Date().toLocaleString("en-US",{timeZone:C.weatherTimezone||"Asia/Jayapura"}))}
function iso(d=now()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function add(n){let d=now();d.setDate(d.getDate()+n);return iso(d)}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function cls(s){s=String(s||"").toLowerCase();if(s.includes("tugas luar")||s.includes("kegiatan luar"))return"outside";if(s.includes("rapat"))return"meeting";if(s.includes("istirahat"))return"break";if(s.includes("cuti")||s.includes("libur"))return"leave";return"office"}
function norm(v){v=String(v||"").trim();if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;let p=v.split(/[\/-]/);if(p.length===3)return p[0].length===4?`${p[0]}-${p[1].padStart(2,"0")}-${p[2].padStart(2,"0")}`:`${p[2]}-${p[1].padStart(2,"0")}-${p[0].padStart(2,"0")}`;return""}
function mins(v){if(!/^\d{1,2}:\d{2}$/.test(String(v||"")))return null;let p=v.split(":").map(Number);return p[0]*60+p[1]}
function curmins(){let d=now();return d.getHours()*60+d.getMinutes()}
function completed(x){if(!C.autoHideCompletedActivities)return false;let e=mins(x.selesai);if(e===null)return false;return curmins()>e+(Number(C.completedActivityGracePeriodMinutes)||0)}
function txt(id,v){let e=document.getElementById(id);if(e)e.textContent=v}
function tick(){let d=now();txt("clock",d.toLocaleTimeString("id-ID",{hour12:false}));txt("fullDate",new Intl.DateTimeFormat("id-ID",{weekday:"long",day:"2-digit",month:"long",year:"numeric"}).format(d))}
async function weather(){let q=new URLSearchParams({latitude:C.weatherLatitude,longitude:C.weatherLongitude,current:"temperature_2m,relative_humidity_2m,is_day,weather_code,wind_speed_10m",timezone:C.weatherTimezone||"Asia/Jayapura"});try{let r=await fetch(`https://api.open-meteo.com/v1/forecast?${q}&_=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw Error();let w=(await r.json()).current;txt("weatherTemp",`${Math.round(w.temperature_2m)}°C`);txt("weatherIcon",icon(w.weather_code,w.is_day));txt("weatherText",`${desc(w.weather_code)} • ${C.weatherLocationName} • RH ${Math.round(w.relative_humidity_2m)}% • Angin ${Math.round(w.wind_speed_10m)} km/j`);txt("weatherUpdated",`Diperbarui ${now().toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"})} WIT`)}catch(e){txt("weatherText","Cuaca belum tersedia • Nabire");txt("weatherUpdated","Periksa koneksi internet")}}
function desc(c){return({0:"Cerah",1:"Cerah berawan",2:"Berawan sebagian",3:"Berawan",45:"Berkabut",48:"Kabut tebal",51:"Gerimis ringan",53:"Gerimis",55:"Gerimis lebat",61:"Hujan ringan",63:"Hujan",65:"Hujan lebat",80:"Hujan lokal ringan",81:"Hujan lokal",82:"Hujan lokal lebat",95:"Hujan petir",96:"Hujan petir",99:"Badai petir"})[c]||"Kondisi cuaca"}
function icon(c,d){if(c===0)return d?"☀️":"🌙";if(c<=2)return"🌤️";if(c===3)return"☁️";if(c===45||c===48)return"🌫️";if(c>=51&&c<=55)return"🌦️";if((c>=61&&c<=65)||(c>=80&&c<=82))return"🌧️";if(c>=95)return"⛈️";return"🌤️"}
async function load(){try{if(C.dataMode==="google-sheet"&&C.googleSheetCsvUrl&&!C.googleSheetCsvUrl.includes("TEMPELKAN_")){let s=C.googleSheetCsvUrl.includes("?")?"&":"?";let r=await fetch(`${C.googleSheetCsvUrl}${s}_=${Date.now()}`,{cache:"no-store"});data=parse(await r.text())}else data=sample()}catch(e){data=sample()}txt("lastRefresh",`Jadwal diperbarui ${now().toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"})} WIT`);render()}
function parse(csv){let rows=[],row=[],cell="",q=false;for(let i=0;i<csv.length;i++){let c=csv[i],n=csv[i+1];if(c=='"'&&q&&n=='"'){cell+='"';i++}else if(c=='"')q=!q;else if(c==","&&!q){row.push(cell);cell=""}else if((c=="\n"||c=="\r")&&!q){if(c=="\r"&&n=="\n")i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=""}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}if(!rows.length)return[];let h=rows.shift().map(x=>x.trim().toLowerCase()),f=(...n)=>n.map(x=>h.indexOf(x)).find(x=>x>=0);return rows.map(r=>({tanggal:norm(r[f("tanggal","date")]),nama:r[f("nama pegawai","nama","pegawai")]||"",divisi:r[f("divisi","unit")]||"",status:r[f("status")]||"Kantor",kegiatan:r[f("kegiatan","agenda")]||"",lokasi:r[f("lokasi","tempat")]||"",mulai:r[f("jam mulai","mulai")]||"",selesai:r[f("jam selesai","selesai")]||""})).filter(x=>x.tanggal&&x.nama)}
function sample(){return[{tanggal:iso(),nama:"Pegawai A",divisi:"Sekretariat",status:"Tugas Luar/Kegiatan Luar",kegiatan:"Kegiatan lapangan",lokasi:"Nabire",mulai:"08:00",selesai:"16:00"},{tanggal:iso(),nama:"Pegawai B",divisi:"Umum",status:"Istirahat",kegiatan:"Istirahat siang",lokasi:"Kantor",mulai:"12:00",selesai:"13:00"}]}
function render(){let a=data.filter(x=>x.tanggal===iso()&&!completed(x)),b=data.filter(x=>x.tanggal===add(1)),n={outside:0,office:0,meeting:0,break:0,leave:0};a.forEach(x=>n[cls(x.status)]++);txt("totalCount",a.length);txt("outsideCount",n.outside);txt("officeCount",n.office);txt("meetingCount",n.meeting);txt("breakCount",n.break);txt("leaveCount",n.leave);activities(a);tomorrow(b);calendar();ongoing(a)}
function activities(a){let e=document.getElementById("activityList"),per=C.itemsPerPage||6,pages=Math.max(1,Math.ceil(a.length/per));page%=pages;if(!a.length){e.innerHTML='<div class="empty"><div><b>Tidak ada kegiatan aktif</b><br><small>Kegiatan yang sudah selesai otomatis disembunyikan.</small></div></div>';clearInterval(pageTimer);dots(1);return}e.innerHTML=a.slice(page*per,page*per+per).map(x=>`<article class="card ${cls(x.status)}"><i class="bar"></i><div><div class="cardtop"><div><div class="person">${esc(x.nama)}</div><div class="division">${esc(x.divisi)}</div></div><span class="tag">${esc(x.status)}</span></div><div class="activity">${esc(x.kegiatan)}</div><div class="meta"><span>📍 ${esc(x.lokasi||"-")}</span><span>🕒 ${esc(x.mulai||"-")} - ${esc(x.selesai||"-")}</span></div></div></article>`).join("");dots(pages);clearInterval(pageTimer);if(pages>1)pageTimer=setInterval(()=>{page=(page+1)%pages;activities(a)},C.pageIntervalMs||12000)}
function dots(n){document.getElementById("pagination").innerHTML=Array.from({length:n},(_,i)=>`<i class="dot ${i===page?"active":""}"></i>`).join("")}
function tomorrow(a){txt("tomorrowDate",new Intl.DateTimeFormat("id-ID",{weekday:"long",day:"2-digit",month:"long"}).format(new Date(add(1)+"T00:00:00")));document.getElementById("tomorrowList").innerHTML=a.length?a.slice(0,5).map(x=>`<div class="tomorrow"><b>${esc(x.nama)}</b><span>${esc(x.kegiatan)} • ${esc(x.lokasi||"-")}</span></div>`).join(""):'<div class="tomorrow"><b>Belum ada agenda</b><span>Jadwal besok belum tersedia.</span></div>'}
function calendar(){let d=now(),y=d.getFullYear(),m=d.getMonth(),start=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate(),events=new Set(data.map(x=>x.tanggal)),c=[];txt("calendarMonth",new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(d));for(let i=start-1;i>=0;i--)c.push([prev-i,true,new Date(y,m-1,prev-i)]);for(let n=1;n<=days;n++)c.push([n,false,new Date(y,m,n)]);let z=1;while(c.length<42)c.push([z,true,new Date(y,m+1,z++)]);document.getElementById("calendarGrid").innerHTML=c.map(x=>{let id=iso(x[2]);return`<div class="day ${x[1]?"muted":""} ${id===iso()?"today":""} ${events.has(id)?"event":""}">${x[0]}</div>`}).join("")}
function ongoing(a){let e=document.getElementById("ongoingBanner"),m=curmins(),o=a.filter(x=>mins(x.mulai)!==null&&mins(x.selesai)!==null&&m>=mins(x.mulai)&&m<=mins(x.selesai));if(o.length){e.classList.remove("hidden");e.textContent="Sedang berlangsung: "+o.slice(0,3).map(x=>`${x.nama} — ${x.kegiatan}`).join(" | ")}else e.classList.add("hidden")}
txt("organizationName",C.organizationName);txt("tickerText",C.tickerText);tick();setInterval(tick,1000);weather();setInterval(weather,C.weatherRefreshIntervalMs||600000);load();setInterval(load,C.scheduleRefreshIntervalMs||60000);setInterval(render,C.activityTimeCheckIntervalMs||30000);